# Generated by Django 2.1.7 on 2020-06-17 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0002_tasklist_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasklist',
            name='manager',
        ),
    ]
